# @format

name: 'Hexo Action Build'

on:
    push:
        branches:
            - master # trigger branch

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install_hexo
              run: |
                  npm i -g hexo-cli # 安装hexo
                  npm i
                  npm install https://github.com/CodeFalling/hexo-asset-image # 图片插件
            - name: generate_hexo
              run: |
                  hexo g
            - name: push_to_pages
              run: |
                  cd ./public
                  git init
                  git config --local user.name "${GITHUB_ACTOR}"
                  git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git add *
                  git commit -m "Update by hexo-action"
                  git push --force  "https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
